### ISSUE TITLE
subcommand links go to wrong page

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/doc.ethsigner#114]
The 3 links on this page https://docs.ethsigner.consensys.net/en/latest/HowTo/Use-Single-Signer/
link to the wrong page. 

- [ ] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [x] Confusing or misleading content
- [ ] Other

## The broken page

 https://docs.ethsigner.consensys.net/en/latest/HowTo/Use-Single-Signer/
## Change suggestion

They should go to
https://docs.ethsigner.consensys.net/en/latest/Reference/CLI/CLI-Subcommands/

**Comment by soham4abc** [comment]
I am willing to work on this issue! if possible pls assign.

**Comment by rolandtyler** [comment]
Fixed in [ConsenSys/doc.ethsigner#119](https://github.com/ConsenSys/doc.ethsigner/pull/119)
