### ISSUE TITLE
Doc how to configure EthSigner for use with Infura 

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/doc.ethsigner#74]
See blog post: https://medium.com/@corgi.desu/a-study-on-blockchain-key-management-systems-part-1-a668eedee058

**Comment by bgravenorst** [comment]
The current documentation does mention how to connect to infura:
https://docs.ethsigner.pegasys.tech/en/latest/Tutorials/Start-EthSigner/#start-ethsigner

See, “If using a cloud-based Ethereum client such as Infura…”

However, we need to rework this content to make it more generic (It's currently very Besu-focussed).
